#!/usr/bin/env python
# Inspired by https://vm.tiktok.com/n4MRdv/

import argparse

alphabets = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
]

combinations = []
for i in alphabets:
    for e in alphabets:
        combinations.append(f"{i}{e}")

# For testing
# for n in range(0, 9):
#     for letters in combinations[0:10]:
#         print(f"https://prnt.sc/{letters}{n:04}")

# Creates a 155MB file approximately 🤔 : Don't open in sublime!!!!!!!!!
with open("all_screenshot_links.txt", mode="w") as f:
    for n in range(0, 9999 + 1):
        for letters in combinations:
            f.write(f"https://prnt.sc/{letters}{n:04}\n")

# Argument approach. Too tired to finish this portion.
# Its 4:00 AM --ish for crying out loud.
# parser = argparse.ArgumentParser(description="Generate screenshot links")
# parser.add_argument(
#     "Range",
#     metavar="range",
#     type=str,
#     help="Range of digits to append to 'https://prnt.sc/<letters>' in the form 0-999",
# )

# args = parser.parse_args()
# range_ = args.Range.split("-")

# start = int(range_[0])
# end = int(range_[1])

# for n in range(start, end):
#     for letters in combinations:
#         print(f"https://prnt.sc/{letters}{n:04}")
